# frozen_string_literal: true

FactoryBot.define do
  factory :admin_user do
    sequence(:email) { |n| "admin#{n}@example.com" }
    password { 'password123' }
    password_confirmation { 'password123' }

    # API token is auto-generated by the model's before_create callback
    # but we can override it for testing specific scenarios

    trait :with_custom_token do
      api_token { SecureRandom.hex(24) }
    end

    trait :without_token do
      # Skip the callback that generates the token
      after(:build) { |user| user.api_token = nil }
    end
  end
end
