# Example credentials file for Twilio Bulk Lookup
# 
# To set up encrypted credentials in your Rails app:
#
# 1. Development:
#    EDITOR="code --wait" rails credentials:edit
#
# 2. Production:
#    EDITOR="code --wait" rails credentials:edit --environment production
#
# Then add your Twilio credentials in this format:

twilio:
  account_sid: ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  auth_token: your_auth_token_here

# Alternative: Use environment variables instead
# Set these in your .env file or hosting platform:
#
# TWILIO_ACCOUNT_SID=ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# TWILIO_AUTH_TOKEN=your_auth_token_here
#
# Note: Using environment variables is recommended for production deployments
# to avoid storing sensitive credentials in the codebase.

# For Heroku:
# heroku config:set TWILIO_ACCOUNT_SID=ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# heroku config:set TWILIO_AUTH_TOKEN=your_auth_token_here

# Redis URL (optional, defaults to localhost)
# redis_url: redis://localhost:6379/0