# frozen_string_literal: true

# Configure SimpleCov for code coverage reporting
# Only start SimpleCov if COVERAGE env var is set or in CI
if ENV['COVERAGE'] || ENV['CI']
  require 'simplecov'
  require 'simplecov-console'

  SimpleCov.start 'rails' do
    # Output formatters
    formatter SimpleCov::Formatter::MultiFormatter.new([
                                                         SimpleCov::Formatter::HTMLFormatter, # HTML report in /coverage
                                                         SimpleCov::Formatter::Console # Terminal output
                                                       ])

    # Filters (exclude from coverage)
    add_filter '/spec/'
    add_filter '/config/'
    add_filter '/vendor/'
    add_filter '/db/'
    add_filter '/bin/'

    # Groups for organization
    add_group 'Controllers', 'app/controllers'
    add_group 'Models', 'app/models'
    add_group 'Services', 'app/services'
    add_group 'Jobs', 'app/jobs'
    add_group 'Admin', 'app/admin'
    add_group 'Helpers', 'app/helpers'
    add_group 'Middleware', 'app/middleware'
    add_group 'Libraries', 'lib'

    # Coverage thresholds (relaxed for initial setup)
    minimum_coverage 60
    minimum_coverage_by_file 40

    # Track files even if not required
    track_files '{app,lib}/**/*.rb'

    # Merge results from parallel test runs
    enable_coverage_for_eval if respond_to?(:enable_coverage_for_eval)
  end
end

# This file was generated by the `rails generate rspec:install` command.
RSpec.configure do |config|
  # Enable expect syntax
  config.expect_with :rspec do |expectations|
    # Include chain clauses in custom matcher descriptions
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
    # Use only expect syntax (no should)
    expectations.syntax = :expect
  end

  # Configure mocking
  config.mock_with :rspec do |mocks|
    # Verify partial doubles to catch typos in method names
    mocks.verify_partial_doubles = true
    # Verify doubled constants exist
    mocks.verify_doubled_constant_names = true
  end

  # Shared context metadata behavior
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # Run focused tests only when :focus tag is present
  config.filter_run_when_matching :focus

  # Persist example status for --only-failures and --next-failure
  config.example_status_persistence_file_path = 'spec/examples.txt'

  # Disable monkey patching (use expect syntax only)
  config.disable_monkey_patching!

  # Use documentation format when running a single file
  config.default_formatter = 'doc' if config.files_to_run.one?

  # Profile the 10 slowest examples
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies
  config.order = :random

  # Seed global randomization for reproducibility
  Kernel.srand config.seed

  # Allow filtering by metadata tags
  config.filter_run_excluding :slow unless ENV['RUN_SLOW_TESTS']

  # Expose DSL globally for convenience
  config.expose_dsl_globally = false

  # Fail fast option (can be enabled via CLI with --fail-fast)
  # config.fail_fast = true

  # Warnings configuration
  config.warnings = false
end
