# frozen_string_literal: true

# Configure SimpleCov for code coverage reporting
require 'simplecov'
require 'simplecov-console'

SimpleCov.start 'rails' do
  # Output formatters
  formatter SimpleCov::Formatter::MultiFormatter.new([
                                                       SimpleCov::Formatter::HTMLFormatter, # HTML report in /coverage
                                                       SimpleCov::Formatter::Console # Terminal output
                                                     ])

  # Filters (exclude from coverage)
  add_filter '/spec/'
  add_filter '/config/'
  add_filter '/vendor/'
  add_filter '/db/'

  # Groups for organization
  add_group 'Controllers', 'app/controllers'
  add_group 'Models', 'app/models'
  add_group 'Services', 'app/services'
  add_group 'Jobs', 'app/jobs'
  add_group 'Admin', 'app/admin'
  add_group 'Helpers', 'app/helpers'

  # Coverage thresholds
  minimum_coverage 80
  minimum_coverage_by_file 60

  # Track files even if not required
  track_files '{app,lib}/**/*.rb'
end

# This file was generated by the `rails generate rspec:install` command.
RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups
  config.filter_run_when_matching :focus
  config.example_status_persistence_file_path = 'spec/examples.txt'
  config.disable_monkey_patching!

  config.default_formatter = 'doc' if config.files_to_run.one?

  config.profile_examples = 10
  config.order = :random
  Kernel.srand config.seed
end
